/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Front Test API
 * Тестовое задание для Frontend разработчика
 * OpenAPI spec version: 1.0
 */
import type { SuccessfulResponse } from "./successfulResponse";
import type { Fetch200AllOf } from "./fetch200AllOf";

export type Fetch200 = SuccessfulResponse & Fetch200AllOf;
