/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Front Test API
 * Тестовое задание для Frontend разработчика
 * OpenAPI spec version: 1.0
 */
import type { Match } from "./match";

export type Fetch200AllOfData = {
  matches: Match[];
};
