/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Front Test API
 * Тестовое задание для Frontend разработчика
 * OpenAPI spec version: 1.0
 */

export * from "./fetch200";
export * from "./fetch200AllOf";
export * from "./fetch200AllOfData";
export * from "./match";
export * from "./matchStatus";
export * from "./player";
export * from "./successfulResponse";
export * from "./successfulResponseData";
export * from "./team";
