/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Front Test API
 * Тестовое задание для Frontend разработчика
 * OpenAPI spec version: 1.0
 */

/**
 * Статус матча
 */
export type MatchStatus = (typeof MatchStatus)[keyof typeof MatchStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MatchStatus = {
  Scheduled: "Scheduled",
  Ongoing: "Ongoing",
  Finished: "Finished",
} as const;
