/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Front Test API
 * Тестовое задание для Frontend разработчика
 * OpenAPI spec version: 1.0
 */
import type { Team } from "./team";
import type { MatchStatus } from "./matchStatus";

export interface Match {
  /** Время проведения матча */
  time: string;
  /** Название матча */
  title: string;
  homeTeam: Team;
  awayTeam: Team;
  /** Счет домашней команды */
  homeScore: number;
  /** Счет гостевой команды */
  awayScore: number;
  status: MatchStatus;
}
