/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Front Test API
 * Тестовое задание для Frontend разработчика
 * OpenAPI spec version: 1.0
 */

export interface Player {
  /** Имя игрока */
  username: string;
  /** Количество убийств */
  kills: number;
}
