/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Front Test API
 * Тестовое задание для Frontend разработчика
 * OpenAPI spec version: 1.0
 */
import type { SuccessfulResponseData } from "./successfulResponseData";

export interface SuccessfulResponse {
  /** Indicated whether the response is successful. */
  ok: boolean;
  /** If successful, response from api */
  data: SuccessfulResponseData;
}
