/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Front Test API
 * Тестовое задание для Frontend разработчика
 * OpenAPI spec version: 1.0
 */
import type { Player } from "./player";

export interface Team {
  /** Название команды */
  name: string;
  players: Player[];
  /** Количество очков */
  points: number;
  /** Место в турнирной таблице */
  place: number;
  /** Количество убийств */
  total_kills: number;
}
